services:
  - type: web
    name: escanerherramientas-prod
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: escanerherramientas_hc7s
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    buildCommand: ""
    startCommand: ""